### ISSUE TITLE
Failed to find Java VM

### ISSUE THREAD

**Issue by govelogo** [jpm4j/jpm4j.installers#1]
I saw the pop-up window with "Failed to find Java VM" while installing on Win 7. Screen shot follows,

C:\Users\me\Downloads>java -jar biz.aQute.jpm.run.jar -g init
post : C:\JPM4J\bin\jpm _postinstall
Home dir      C:\JPM4J
Bin  dir      C:\JPM4J\bin
Error
1. Failed to run platform init, exit code -2147483648.
   stdout: -------------------------------------------------------------

Any ideas? is this a java installation issue? (My java is version 7; but not installed via java installer)

Thanks!
David

**Comment by pkriens** [comment]
jpm is looking for the vm in the windows registry. If it is not properly listed there, where should I look?

Kind regards,

```
Peter Kriens
```

**Comment by govelogo** [comment]
Hi Peter

Why can't jpm use JAVA_HOME or JRE_HOME? But even I installed java 8 from
installer (on a win 7 64bit), jpm install exe still complains not finding
JVM. Cheers

thanks,
--David

**Comment by pkriens** [comment]
Unfortunately I am too busy to investigate the windows issues at the moment (that is why it is not production yet :-( ) I've made a note and next time I am in the Windows part (which I am awfully bad at due to a dislike dating back to the eighties) I will take a deeper look. 

Since this is open source ... I am using winrun4j (http://winrun4j.sourceforge.net/) as the base for running Java on Windows, and the source code is here: https://github.com/bndtools/bnd/blob/master/biz.aQute.jpm/src/aQute/jpm/platform/Windows.java

If you have a patch I would be more than welcome to integrate it.

Kind regards,

```
Peter Kriens
```

**Comment by govelogo** [comment]
I have got bnd from github. So I will move on. But if I need to come back
to jpm again, I will definitely try to get to the bottom of it. Cheers

thanks,
--David

**Comment by pkriens** [comment]
Thanks, any help would be greatly appreciated ... 

Kind regards,

```
Peter Kriens
```

**Comment by AndyWu2015** [comment]
winrun4j find jre in windows registry and if user doesn't install jre or the configuration is wrong , the jpm will fail to install. So we can just install jre to fix this problem.

**Comment by pkriens** [comment]
so we can close this?

**Comment by AndyWu2015** [comment]
I am ok with that :)

**Comment by AndyWu2015** [comment]
Hi @pkriens  , I've finished a change in jpm (I know it is going to be removed , but I think it is a pretty good lib for command line development ), I drop winrun4j.exe on windows and make a bat file for wrapper launch jar file on windows , following is the sample content, 

@echo off
java -DJPMREPO=C:\Users\Administrator\.jpm\windows\repo  -cp "C:\Users\Administrator\.jpm\windows\repo\2AAE465202E21AF3F2BC7E11DC813C48A107CAD6;C:\Users\Administrator\.jpm\windows\repo\service.jar" aQute.jpm.main.Main %*

I don't know why you choose winrun4j firstly , but I found the bat way works well also.
I do this post just ask your suggestion, are you ok with such solution ? or you've found some thing bad with the bat way , please share with us, thanks.

**Comment by pkriens** [comment]
The jpm command line will remain in bnd. Winrun4j was used because it handles the security mess on Windows better.

**Comment by AndyWu2015** [comment]
Glad to know that.
And thanks for the reply.
